// packages/solid/src/ui/Navigator.tsx
import { onNavigation } from '@magicdoor/magic-use-case-core';
import { onCleanup } from 'solid-js';

export interface NavigatorProps {
  onNavigate?: (url: string) => void;
}

export const Navigator = (props: NavigatorProps) => {
  const unsubscribe = onNavigation((url) => {
    if (url) {
      props.onNavigate?.(url);
    }
  });

  onCleanup(unsubscribe);

  return null;
};

// packages/react/src/ui/Navigator.tsx
import { onNavigation } from '@magicdoor/magic-use-case-core';
import { useEffect, type FC } from 'react';

interface NavigatorProps {
  onNavigate?: (url: string) => void;
}

export const Navigator: FC<NavigatorProps> = (props: NavigatorProps) => {
  useEffect(() => {
    return onNavigation((url) => {
      if (url) {
        props.onNavigate?.(url);
      }
    });
  }, [props.onNavigate]);

  return null;
};
