// packages/react/src/hooks/usePresenter.ts
import { type Presenter } from '@magic-use-case/core';
import { useEffect, useRef, useCallback } from 'react';
import { useReconciledStore } from './reconciledStore';

export function usePresenter<T extends object>(PresenterClass: new () => Presenter<T>) {
  const [model, setModel] = useReconciledStore<T | undefined>(undefined);

  const presenterRef = useRef<Presenter<T>>(undefined);
  if (!presenterRef.current) {
    presenterRef.current = new PresenterClass();
  }

  const updateModel = useCallback(
    (newModel: T | undefined) => {
      setModel(newModel);
    },
    [setModel]
  );

  useEffect(() => {
    if (!presenterRef.current) return;
    presenterRef.current.subscribe(updateModel);
    return () => {
      presenterRef.current?.unsubscribe(updateModel);
      presenterRef.current?.destroy();
      presenterRef.current = undefined;
    };
  }, [updateModel]);
  return { model };
}

// packages/solid/src/hooks/usePresenter.ts
import { type Presenter } from '@magic-use-case/core';
import { onCleanup } from 'solid-js';
import type { Accessor } from 'solid-js';
import { createReconciledStore } from './reconciledStore';

export function usePresenter<T extends object>(PresenterClass: new () => Presenter<T>): { model: Accessor<T | undefined> } {
  const [model, setModel] = createReconciledStore<{ value: T | undefined }>({ value: undefined });

  const presenter = new PresenterClass();

  const updateModel = (newModel?: T) => {
    setModel({ value: newModel });
  };

  presenter.subscribe(updateModel);

  onCleanup(() => {
    presenter.unsubscribe(updateModel);
    presenter.destroy();
  });

  return { model: () => model.value };
}
